// Candidatos ao artilheiro — lista curada por seleção
export const ARTILHEIRO_CANDIDATES: Array<{ player: string; team: string; iso: string }> = [
  { player: 'Kylian Mbappé',       team: 'França',           iso: 'fr' },
  { player: 'Erling Haaland',      team: 'Noruega',          iso: 'no' },
  { player: 'Harry Kane',          team: 'Inglaterra',       iso: 'gb-eng' },
  { player: 'Vinícius Jr.',        team: 'Brasil',           iso: 'br' },
  { player: 'Lionel Messi',        team: 'Argentina',        iso: 'ar' },
  { player: 'Cristiano Ronaldo',   team: 'Portugal',         iso: 'pt' },
  { player: 'Julián Álvarez',      team: 'Argentina',        iso: 'ar' },
  { player: 'Rodrygo',             team: 'Brasil',           iso: 'br' },
  { player: 'Álvaro Morata',       team: 'Espanha',          iso: 'es' },
  { player: 'Lamine Yamal',        team: 'Espanha',          iso: 'es' },
  { player: 'Darwin Núñez',        team: 'Uruguai',          iso: 'uy' },
  { player: 'Santiago Giménez',    team: 'México',           iso: 'mx' },
  { player: 'Jonathan David',      team: 'Canadá',           iso: 'ca' },
  { player: 'Luis Díaz',           team: 'Colômbia',         iso: 'co' },
  { player: 'Florian Wirtz',       team: 'Alemanha',         iso: 'de' },
  { player: 'Jamal Musiala',       team: 'Alemanha',         iso: 'de' },
  { player: 'Cody Gakpo',          team: 'Países Baixos',    iso: 'nl' },
  { player: 'Marcus Thuram',       team: 'França',           iso: 'fr' },
  { player: 'Romelu Lukaku',       team: 'Bélgica',          iso: 'be' },
  { player: 'Antoine Griezmann',   team: 'França',           iso: 'fr' },
  { player: 'Youssef En-Nesyri',   team: 'Marrocos',         iso: 'ma' },
  { player: 'Takumi Minamino',     team: 'Japão',            iso: 'jp' },
  { player: 'Heung-min Son',       team: 'Coreia do Sul',    iso: 'kr' },
  { player: 'Mohamed Salah',       team: 'Egito',            iso: 'eg' },
  { player: 'Mohammed Kudus',      team: 'Gana',             iso: 'gh' },
  { player: 'Christian Pulisic',   team: 'Estados Unidos',   iso: 'us' },
  { player: 'Sadio Mané',          team: 'Senegal',          iso: 'sn' },
  { player: 'Achraf Hakimi',       team: 'Marrocos',         iso: 'ma' },
  { player: 'Viktor Gyökeres',     team: 'Suécia',           iso: 'se' },
  { player: 'Kai Havertz',         team: 'Alemanha',         iso: 'de' },
  { player: 'Breel Embolo',        team: 'Suíça',            iso: 'ch' },
  { player: 'Ciro Immobile',       team: 'Itália',           iso: 'it' },
  { player: 'Riyad Mahrez',        team: 'Argélia',          iso: 'dz' },
  { player: 'Sardar Azmoun',       team: 'Irã',              iso: 'ir' },
  { player: 'Salem Al-Dawsari',    team: 'Arábia Saudita',   iso: 'sa' },
  { player: 'Thomas Partey',       team: 'Gana',             iso: 'gh' },
  { player: 'Alphonso Davies',     team: 'Canadá',           iso: 'ca' },
  { player: 'Luka Modrić',         team: 'Croácia',          iso: 'hr' },
  { player: 'Federico Valverde',   team: 'Uruguai',          iso: 'uy' },
  { player: 'Phil Foden',          team: 'Inglaterra',       iso: 'gb-eng' },
  { player: 'Bukayo Saka',         team: 'Inglaterra',       iso: 'gb-eng' },
  { player: 'Bernardo Silva',      team: 'Portugal',         iso: 'pt' },
  { player: 'Bruno Fernandes',     team: 'Portugal',         iso: 'pt' },
  { player: 'Arda Güler',          team: 'Turquia',          iso: 'tr' },
  { player: 'Moisés Caicedo',      team: 'Equador',          iso: 'ec' },
  { player: 'James Rodríguez',     team: 'Colômbia',         iso: 'co' },
  { player: 'Hirving Lozano',      team: 'México',           iso: 'mx' },
  { player: 'Takefusa Kubo',       team: 'Japão',            iso: 'jp' },
  { player: 'Pedri',               team: 'Espanha',          iso: 'es' },
  { player: 'Rodri',               team: 'Espanha',          iso: 'es' },
]
